# Generated by Django 5.2.16 on 2026-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('career_domain', models.CharField(max_length=100)),
                ('skills_required', models.TextField()),
                ('tags', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
