# Generated by Django 5.2.16 on 2026-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterField(
            model_name='course',
            name='skills_required',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.TextField(help_text='Comma-separated keywords used for ML matching'),
        ),
    ]
